
tasks:
  - init: >
      chmod +x dotnet-install.sh &&
      ./dotnet-install.sh -c Current --install-dir "$HOME/.dotnet" &&
      echo 'export PATH=$PATH:$HOME/.dotnet' >> ~/.bashrc

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-dotnettools.vscode-dotnet-runtime
    - jsw.csharpextensions
